nginx:
    image: nginx:latest
    ports:
        - "10080:80"
        - "10443:443"
    links:
        - upstream
    volumes:
        - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
        - upstream
    restart: always

postgres:
    image: postgres:latest
    ports:
        - "15432:5432"
    environment:
        - POSTGRES_USER=quapee
        - POSTGRES_PASSWORD=password
    restart: always

memcached:
    image: memcached:latest

upstream:
    build: ./etc/php
    links:
        - postgres
        - memcached
    environment:
        - USE_DOTENV=1
    volumes:
        - .:/var/www/html
        - ./var/bootstrap.php.cache:/var/www/html/var/bootstrap.php.cache
        - ./var/SymfonyRequirements.php:/var/www/html/var/SymfonyRequirements.php
    volumes_from:
        - upstream_data

upstream_data:
    image: tianon/true
    volumes:
        - /tmp:/var/www/html/var
