<?php

namespace QuapeeBundle\Repository;

/**
 * FrontendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontendRepository extends \Doctrine\ORM\EntityRepository
{
}
