services:
    quapee.request_validator:
        class: QuapeeBundle\Proxy\Core\RequestValidator
    quapee.request_factory:
        class: QuapeeBundle\Proxy\Core\RequestFactory
        arguments: ['@quapee.request_validator']
    quapee.credential_repository:
        class: QuapeeBundle\Proxy\Impl\DatabaseCredentialRepository
        arguments: ['@doctrine.dbal.default_connection']
    quapee.service_factory:
        class: QuapeeBundle\Proxy\Impl\SoapServiceFactory
        arguments: ['@quapee.credential_repository']
    quapee.proxy:
        class: QuapeeBundle\Proxy\Core\Proxy
        arguments: ['@quapee.request_factory', '@quapee.service_factory']
